dist: trusty
sudo: required

language: python
python:
  - "2.7.14"

install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls

script:
  - python palindromes-test.py
  - pylint paindromes.py
  - pycodestyle paindromes.py
  - py.test --cov=.
  - coverage report

after_success:
  coveralls